"""added a comments table

Revision ID: 56726acfef0f
Revises: 8d280eeda247
Create Date: 2018-04-20 12:01:39.204999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56726acfef0f'
down_revision = '8d280eeda247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
