"""created a one to many relationship 

Revision ID: 78d3e29d4656
Revises: 56726acfef0f
Create Date: 2018-04-20 22:29:18.407868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d3e29d4656'
down_revision = '56726acfef0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'comment_id')
    # ### end Alembic commands ###
